<a href="https://colab.research.google.com/github/chilakala-jahnavi/Customer_Segmentation_and_CLV_Analysis/blob/main/Customer_Segmentation_%26_CLV_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [7]:
df = pd.read_csv("/content/sample_data/digital_wallet_ltv_dataset.csv")

In [13]:
df.head()

  Customer_ID  Age  ... Customer_Satisfaction_Score           LTV
0   cust_0000   54  ...                           1  3.279546e+05
1   cust_0001   67  ...                           8  1.437053e+06
2   cust_0002   44  ...                           4  2.419387e+05
3   cust_0003   30  ...                           1  1.284599e+05
4   cust_0004   58  ...                           5  9.569514e+05

[5 rows x 20 columns]

In [14]:
df.shape

(7000, 20)

In [15]:
df.columns

Index(['Customer_ID', 'Age', 'Location', 'Income_Level', 'Total_Transactions',
       'Avg_Transaction_Value', 'Max_Transaction_Value',
       'Min_Transaction_Value', 'Total_Spent', 'Active_Days',
       'Last_Transaction_Days_Ago', 'Loyalty_Points_Earned', 'Referral_Count',
       'Cashback_Received', 'App_Usage_Frequency', 'Preferred_Payment_Method',
       'Support_Tickets_Raised', 'Issue_Resolution_Time',
       'Customer_Satisfaction_Score', 'LTV'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  7000 non-null   object
 1   Age                          7000 non-null   int64
 2   Location                     7000 non-null   object
 3   Income_Level                 7000 non-null   object
 4   Total_Transactions           7000 non-null   int64
 5   Avg_Transaction_Value        7000 non-null   float64
 6   Max_Transaction_Value        7000 non-null   float64
 7   Min_Transaction_Value        7000 non-null   float64
 8   Total_Spent                  7000 non-null   float64
 9   Active_Days                  7000 non-null   int64
 10  Last_Transaction_Days_Ago    7000 non-null   int64
 11  Loyalty_Points_Earned        7000 non-null   int64
 12  Referral_Count               7000 non-null   int64
 13  Cashback_Received            7000 non-null   float64
 14  App_Usage_Frequency          7000 non-null   object
 15  Preferred_Payment_Method     7000 non-null   object
 16  Support_Tickets_Raised       7000 non-null   int64
 17  Issue_Resolution_Time        7000 non-null   float64
 18  Customer_Satisfaction_Score  7000 non-null   int64
 19  LTV                          7000 non-null   float64
dtypes: float64(7), int64(8), object(5)
memory usage: 1.1+ MB

In [19]:
df.describe()

               Age  ...           LTV
count  7000.000000  ...  7.000000e+03
mean     42.633714  ...  5.119197e+05
std      15.516036  ...  4.390551e+05
min      16.000000  ...  3.770495e+03
25%      29.000000  ...  1.482058e+05
50%      43.000000  ...  3.878180e+05
75%      56.000000  ...  7.748578e+05
max      69.000000  ...  1.956988e+06

[8 rows x 15 columns]